// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmgjplrejeslnqyoagvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ2pwbHJlamVzbG5xeW9hZ3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjQ3OTUsImV4cCI6MjA3MDM0MDc5NX0.6KgrmQ6Urdcvs5yPexpU-OPMIp3chRusQ4Fya0MHWeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});